services:
  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    depends_on:
      - orchestrator
    networks:
      - back
    environment:
      - ADDR_ORCHESTRATOR=orchestrator
      - PORT_ORCHESTRATOR=8080
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - '8080:8080'
      - '50051:50051'
    networks:
      - back
      - front
    environment:
      - ADDR_ORCHESTRATOR=0.0.0.0
      - PORT_ORCHESTRATOR=8080
networks:
  front:
    driver: bridge
  back:
    driver: bridge
