// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: calculation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WrappedDouble struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Поле optional создаст *float64 в Go
	Value         *float64 `protobuf:"fixed64,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrappedDouble) Reset() {
	*x = WrappedDouble{}
	mi := &file_calculation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappedDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedDouble) ProtoMessage() {}

func (x *WrappedDouble) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedDouble.ProtoReflect.Descriptor instead.
func (*WrappedDouble) Descriptor() ([]byte, []int) {
	return file_calculation_proto_rawDescGZIP(), []int{0}
}

func (x *WrappedDouble) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type TaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID - Уникальный идентификатор задачи.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Args - Срез указателей на аргументы задачи.
	Args []*WrappedDouble `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Operation - Операция, которую необходимо выполнить.
	Operation string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	// Expression - ID выражения, к которому принадлежит данная задача.
	Expression int64 `protobuf:"varint,4,opt,name=expression,proto3" json:"expression,omitempty"`
	// Error - Указывает на ошибку вычисления задачи
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_calculation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_calculation_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskResponse) GetArgs() []*WrappedDouble {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TaskResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TaskResponse) GetExpression() int64 {
	if x != nil {
		return x.Expression
	}
	return 0
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskCompleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression - ID корневого выражения, к которому принадлежит задача.
	Expression int64 `protobuf:"varint,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// ID - Уникальный идентификатор задачи.
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Result - Результат вычисления задачи.
	Result float64 `protobuf:"fixed64,3,opt,name=result,proto3" json:"result,omitempty"`
	// Error - Указывает на невыполнимость задачи
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompleted) Reset() {
	*x = TaskCompleted{}
	mi := &file_calculation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleted) ProtoMessage() {}

func (x *TaskCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleted.ProtoReflect.Descriptor instead.
func (*TaskCompleted) Descriptor() ([]byte, []int) {
	return file_calculation_proto_rawDescGZIP(), []int{2}
}

func (x *TaskCompleted) GetExpression() int64 {
	if x != nil {
		return x.Expression
	}
	return 0
}

func (x *TaskCompleted) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskCompleted) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_calculation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_calculation_proto_rawDescGZIP(), []int{3}
}

var File_calculation_proto protoreflect.FileDescriptor

const file_calculation_proto_rawDesc = "" +
	"\n" +
	"\x11calculation.proto\x12\vcalculation\"4\n" +
	"\rWrappedDouble\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x01H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xa2\x01\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04args\x18\x02 \x03(\v2\x1a.calculation.WrappedDoubleR\x04args\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\x03R\n" +
	"expression\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"m\n" +
	"\rTaskCompleted\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\x03R\n" +
	"expression\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x01R\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\a\n" +
	"\x05Empty2\x8f\x01\n" +
	"\x13OrchestratorService\x128\n" +
	"\aGetTask\x12\x12.calculation.Empty\x1a\x19.calculation.TaskResponse\x12>\n" +
	"\fSubmitResult\x12\x1a.calculation.TaskCompleted\x1a\x12.calculation.EmptyB'Z%github.com/OinkiePie/calc_3/pkg/protob\x06proto3"

var (
	file_calculation_proto_rawDescOnce sync.Once
	file_calculation_proto_rawDescData []byte
)

func file_calculation_proto_rawDescGZIP() []byte {
	file_calculation_proto_rawDescOnce.Do(func() {
		file_calculation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculation_proto_rawDesc), len(file_calculation_proto_rawDesc)))
	})
	return file_calculation_proto_rawDescData
}

var file_calculation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculation_proto_goTypes = []any{
	(*WrappedDouble)(nil), // 0: calculation.WrappedDouble
	(*TaskResponse)(nil),  // 1: calculation.TaskResponse
	(*TaskCompleted)(nil), // 2: calculation.TaskCompleted
	(*Empty)(nil),         // 3: calculation.Empty
}
var file_calculation_proto_depIdxs = []int32{
	0, // 0: calculation.TaskResponse.args:type_name -> calculation.WrappedDouble
	3, // 1: calculation.OrchestratorService.GetTask:input_type -> calculation.Empty
	2, // 2: calculation.OrchestratorService.SubmitResult:input_type -> calculation.TaskCompleted
	1, // 3: calculation.OrchestratorService.GetTask:output_type -> calculation.TaskResponse
	3, // 4: calculation.OrchestratorService.SubmitResult:output_type -> calculation.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_calculation_proto_init() }
func file_calculation_proto_init() {
	if File_calculation_proto != nil {
		return
	}
	file_calculation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculation_proto_rawDesc), len(file_calculation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculation_proto_goTypes,
		DependencyIndexes: file_calculation_proto_depIdxs,
		MessageInfos:      file_calculation_proto_msgTypes,
	}.Build()
	File_calculation_proto = out.File
	file_calculation_proto_goTypes = nil
	file_calculation_proto_depIdxs = nil
}
